image: docker:19.03
services:
- docker:19.03-dind
before_script:
- apk --no-cache -q add curl jq
variables:
  CI_REGISTRY_IMAGE: antora/antora
  CI_REGISTRY_TAGS_RESOURCE: https://registry.hub.docker.com/v2/repositories/$CI_REGISTRY_IMAGE/tags/?page_size=25
.defs:
- &set_antora_version
  ANTORA_VERSION=${ANTORA_VERSION:-$(curl -s 'https://gitlab.com/api/v4/projects/4180516/repository/tags?order_by=updated&sort=desc&per_page=1' | jq -rM '.[].name[1:]')}
  echo "Antora version resolved: $ANTORA_VERSION"
- &sub_antora_version
  sed -i "s/@latest/@$ANTORA_VERSION/g" Dockerfile
- &sub_node_version |
  [ ${ANTORA_VERSION%%.*} -lt 3 ] && sed -i "s/^FROM node:16-/FROM node:10-/" Dockerfile
- &docker_build
  docker build --pull -t "$CI_REGISTRY_IMAGE:$ANTORA_VERSION" .
- &docker_list_image
  docker images "$CI_REGISTRY_IMAGE:$ANTORA_VERSION"
build:
  stage: build
  except:
  - main@antora/docker-antora
  script:
  - *set_antora_version
  - *sub_antora_version
  - *sub_node_version
  - *docker_build
  - *docker_list_image
deploy:
  stage: deploy
  only:
  - main@antora/docker-antora
  script:
  - |
    echo "Antora version requested: ${ANTORA_VERSION:-none}"
  - *set_antora_version
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  - docker pull "$CI_REGISTRY_IMAGE:$ANTORA_VERSION"
  - docker tag "$CI_REGISTRY_IMAGE:$ANTORA_VERSION" "$CI_REGISTRY_IMAGE:testing"
  - docker push "$CI_REGISTRY_IMAGE:testing"
  #- *sub_antora_version
  #- *sub_node_version
  #- *docker_build
  #- *docker_list_image
  #- |
  #  while [ -n $CI_REGISTRY_TAGS_RESOURCE ]; do
  #    _tags=$(curl -s $CI_REGISTRY_TAGS_RESOURCE)
  #    _published=$(echo $_tags | jq -rM '.results[].name | select(. == "'$ANTORA_VERSION'")')
  #    if [ -n $_published ]; then
  #      echo "Skipping publishing. $CI_REGISTRY_IMAGE:$ANTORA_VERSION has already been published."
  #      exit 0
  #    else
  #      CI_REGISTRY_TAGS_RESOURCE=$(echo $_tags | jq -rM '.next')
  #    fi
  #  done
  #- echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  #- echo "Publishing $CI_REGISTRY_IMAGE:$ANTORA_VERSION"
  #- docker push "$CI_REGISTRY_IMAGE:$ANTORA_VERSION"
  #- if [ -z "${ANTORA_VERSION/*-*}" ]; then CI_REGISTRY_IMAGE_TAG=testing; else CI_REGISTRY_IMAGE_TAG=latest; fi
  #- echo "Tagging $CI_REGISTRY_IMAGE:$ANTORA_VERSION as $CI_REGISTRY_IMAGE_TAG"
  #- docker tag "$CI_REGISTRY_IMAGE:$ANTORA_VERSION" "$CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_TAG"
  #- docker push "$CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_TAG"
