build:
  stage: build
  only:
  - master@antora/docker-antora
  image: docker:18.09
  services:
  - docker:18.09-dind
  before_script:
  - apk --no-cache -q add curl jq
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
  - export ANTORA_VERSION=$(curl -s https://gitlab.com/api/v4/projects/4180516/repository/tags | jq -r 'first(.[].name[1:] | select(contains("-") | not))')
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$ANTORA_VERSION"
  - docker push "$CI_REGISTRY_IMAGE:$ANTORA_VERSION"
  - docker push "$CI_REGISTRY_IMAGE:latest"
