= Modifying and Pushing this image to Docker Hub
:version: 0.13

== Building the base image

  $ docker build --pull -t danyill/antora-base:custom .

== Building the next image

We build the image like so:

  $ docker build -t danyill/antora:custom -f Dockerfile.custom .

We tag the image as latest and the next version:

[subs="+attributes"]
  $ docker tag danyill/antora:custom danyill/antora:{version}
  $ docker tag danyill/antora:custom danyill/antora:latest

Together:

[subs="+attributes"]
  $ docker tag danyill/antora:custom danyill/antora:{version} && docker tag danyill/antora:custom danyill/antora:latest

We ensure that we are logged in to the Docker Hub:

  $ docker login

We push a `latest` tag and the version (current increments are `0.1`):

[subs="+attributes"]
  $ docker push danyill/antora:{version} # or whatever your version
  $ docker push danyill/antora:latest

or 

[subs="+attributes"]
  $ docker push danyill/antora:{version} && docker push danyill/antora:latest

We then commit the chawnges and push a tag to our git repository:

[subs="+attributes"]
  $ git tag v{version} -s -m "A relevant message"
  $ git push --tags 

== From scratch

  $ docker build --pull --no-cache -t danyill/antora-base:custom -f Dockerfile .

To ensure updates all the way (e.g. an update of the core image):

  $ docker build --no-cache -t danyill/antora:custom -f Dockerfile.custom .

