FROM danyill/antora-base:custom

RUN yarn global add asciidoctor-kroki
RUN yarn global add @antora/lunr-extension
RUN yarn global add xlsx
RUN yarn global add @antora/pdf-extension

RUN apt-get update && apt-get install -y ruby \
    && gem install asciidoctor-pdf asciidoctor-kroki rouge
